services:
  - name: backup-db
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: replace-with-your-postgres-instance-name
          property: connectionString
      # Cloudflare R2 endpoint URL
      - key: R2_ENDPOINT
        sync: false 
      # A globally unique name for your bucket
      # For example, <your-username>-<database name>-render-postgres-backups
      - key: R2_BUCKET_NAME
        sync: false
      # Your Cloudflare R2 Access Key ID
      - key: AWS_ACCESS_KEY_ID
        sync: false
      # Your Cloudflare R2 Secret Access Key
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # Postgres version of your Postgres instance 
      # For example, 16
      - key: POSTGRES_VERSION
        sync: false
      # Alpine base-OS version, see README
      # For example, 3.20
      - key: ALPINE_VERSION
        sync: false

